import { test, expect } from '@playwright/test';
test.beforeEach(async ({ page }) => {
  page.on('pageerror', (error) => console.error('Application browser error:', error.message));
});
test('Dependency disruption, investigation, evidence exports, and live separation', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/?vertical=public_services');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('button', { name: '3 Impact', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Shared identity, Critical, inspect evidence', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Shared identity, Critical, inspect evidence', exact: true }).click();
  await expect(page.getByText('Shared identity latency', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: '✧ Investigation assistant', exact: true }).click();
  await page.getByRole('button', { name: /^Investigate the current issue and its dependency impact/ }).click();
  await expect(page.getByText('Investigation steps', { exact: true })).toBeVisible();
  await expect(page.locator('summary').filter({ hasText: 'follow dependencies' })).toBeVisible();
  await page.locator('summary').filter({ hasText: 'query events' }).click();
  await expect(page.locator('pre').last()).toContainText('facility_ops_demo_events');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export evidence', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('operations-investigation.json');
  await page.getByRole('button', { name: 'Live', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Live data requires this app to be installed in Splunk');
  await expect(page.getByText('Investigation steps', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'artifacts/browser-tests/live-separation.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('Provider settings and supervised demo action stay explicit', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('button', { name: '3 Impact', exact: true }).click();
  await page.getByRole('button', { name: '⚙ Settings', exact: true }).click();
  await page.getByRole('combobox', { name: /LLM provider/ }).selectOption('openai');
  await expect(page.getByLabel('OpenAI API key', { exact: false })).toBeDisabled();
  await page.getByRole('combobox', { name: /LLM provider/ }).selectOption('demo');
  await page.getByRole('button', { name: 'Save provider settings', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Preview settings updated');
  await page.getByRole('button', { name: '↗ Action workspace', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Run simulation', exact: true })).toBeDisabled();
  await page.getByRole('combobox', { name: /Autonomy policy/ }).selectOption('supervised');
  await page.getByRole('button', { name: 'Record demo approval', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Run simulation', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Run simulation', exact: true }).click();
  await expect(page.getByText('Simulated execution completed; recovery verification required', { exact: false })).toBeVisible();
  await page.screenshot({ path: 'artifacts/browser-tests/supervised-action.png', fullPage: true });
});
test('Verticals and audience workflows adapt, including compact navigation', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Presentation settings', exact: true }).click();
  await page.getByRole('combobox', { name: /Industry \/ vertical/ }).selectOption('distributed_care');
  await page.getByRole('combobox', { name: /Audience/ }).selectOption('isso');
  await expect(page.getByRole('heading', { name: 'Presentation setup', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Apply presentation', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Current evidence and accountability', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Clinical workflow', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 750, height: 1000 });
  await page.getByRole('combobox', { name: /Workspace view/ }).selectOption('investigate');
  await expect(page.getByRole('heading', { name: 'Operations investigation assistant', exact: true })).toBeVisible();
  await page.screenshot({ path: 'artifacts/browser-tests/compact-assistant.png', fullPage: true });
});
test('Commercial presentation setup applies atomically, remembers context and keeps the dashboard clean', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('combobox', { name: 'Audience', exact: true })).toHaveCount(0);
  await expect(page.getByRole('combobox', { name: 'Use case', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await page.getByRole('button', { name: '3 Impact', exact: true }).click();
  await page.getByRole('button', { name: 'Presentation settings', exact: true }).click();
  await page.getByRole('combobox', { name: 'Industry / vertical', exact: true }).selectOption('retail');
  await page.getByRole('combobox', { name: 'Audience', exact: true }).selectOption('executive');
  await expect(page.getByRole('combobox', { name: 'Use case', exact: true })).toHaveValue('dependency');
  await expect(page.getByRole('combobox', { name: 'Use case', exact: true })).toContainText('Checkout and Fulfillment Access');
  await expect(page.getByLabel('Current presentation context')).toContainText('Enterprise Shared Services');
  await page.getByRole('button', { name: 'Apply presentation', exact: true }).click();
  await expect(page.getByLabel('Current presentation context')).toContainText('Retail and Commerce');
  await expect(page.getByLabel('Current presentation context')).toContainText('Executive');
  await expect(page.getByRole('button', { name: 'Online checkout', exact: true })).toBeVisible();
  await expect(page.getByText('Customer and fulfillment sign-in latency', { exact: true })).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Audience', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: '✧ Investigation assistant', exact: true }).click();
  await page.getByRole('button', { name: /^Investigate the current issue and its dependency impact/ }).click();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export evidence', exact: true }).click();
  const file = await download;
  const { readFile } = await import('node:fs/promises');
  const exported = JSON.parse(await readFile((await file.path())!, 'utf8'));
  expect(exported.scope.vertical).toBe('retail');
  expect(exported.scope.audience).toBe('executive');
  expect(exported.results[0].rows.some((row: { name: string }) => row.name === 'Online checkout')).toBe(true);
  await page.reload();
  await expect(page.getByLabel('Current presentation context')).toContainText('Retail and Commerce');
  await expect(page.getByLabel('Current presentation context')).toContainText('Executive');
  await page.getByRole('button', { name: 'Present', exact: true }).click();
  await page.getByRole('button', { name: 'Presentation settings', exact: true }).click();
  await page.getByRole('combobox', { name: 'Industry / vertical', exact: true }).selectOption('manufacturing');
  await page.getByRole('combobox', { name: 'Use case', exact: true }).selectOption('facility');
  await page.getByRole('combobox', { name: 'Audience', exact: true }).selectOption('facilities');
  await page.getByRole('button', { name: 'Apply presentation', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Manufacturing plant', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Central campus', exact: true })).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Presentation settings', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Apply presentation', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'artifacts/browser-tests/commercial-settings-mobile.png', fullPage: true });
  await page.goto('/?vertical=public_services&audience=operations&usecase=dependency');
  await expect(page.getByLabel('Current presentation context')).toContainText('Public Services and Benefits');
  await expect(page.getByLabel('Current presentation context')).toContainText('Operations');
  expect(errors).toEqual([]);
});
