[script:facility_ops_agent]
match = /facility_ops/agent
script = facility_ops_rest.py
scripttype = persist
handler = facility_ops_rest.FacilityOperations
python.version = python3.9
python.required = 3.9,3.13
passSession = true
requireAuthentication = true
capability = search
passSystemAuth = true
output_modes = json

[script:facility_ops_settings]
match = /facility_ops/settings
script = facility_ops_rest.py
scripttype = persist
handler = facility_ops_rest.FacilityOperations
python.version = python3.9
python.required = 3.9,3.13
passSession = true
requireAuthentication = true
capability = search
passSystemAuth = true
output_modes = json
